import Head from "next/head";
import Image from "next/image";
import Categories from "../Components/Elements/Categories";
import Hero from "../Components/Elements/Hero";
import Jeeps from "../Components/Elements/Jeeps";
import Patners from "../Components/Elements/Patners";
import Personalized from "../Components/Elements/Personalized";
import Revolution from "../Components/Elements/Revolution";
import Ship from "../Components/Elements/Ship";
import Tickets from "../Components/Elements/Tickets";
import Vision from "../Components/Elements/Vision";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Hero />
      <Revolution />
      <Categories />
      <Tickets />
      <Personalized />
      <Vision />
      <Patners />
      <Ship />
      <Jeeps />
    </div>
  );
}
